FROM gradle:8.14-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :apps:transcoder:bootJar --no-daemon

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/apps/transcoder/build/libs/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]